image: maven:3.5.4-jdk-10-slim

pipelines:
  branches:
    chapter*:
      - step:
          caches:
            - maven
          script: # Modify the commands below to build your repository.
            - mvn -B verify -DforkCount=0 # -B batch mode makes Maven less verbose
